services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=dainius
      - POSTGRES_PASSWORD=Passw0rd!
      - POSTGRES_DB=tutorial
    ports:
      - "5432"
  web:
    build: .
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - .:/code
    links:
      - db
    depends_on:
      - db
